import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import worfoto from '@/public/images/worfoto.jpg'
import { FaGithub,FaLinkedin } from "react-icons/fa";
import {IoConstructOutline } from "react-icons/io5";
import {AiFillProject} from 'react-icons/ai'


const inter = Inter({ subsets: ['latin'] })

const gitGif = '/public/images/gitHub.gif'

export default function Home() {
  return <>
    <Head>
      <title>Worley Sacramento</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={`${styles.main} ${inter.className}`}>
      <div className={styles.description}>
        <p>
         Olá, seja bem vindo(a)
        </p>
        <div className={styles.profile}>
            {/* <Image
              src={worfoto}
              alt="Vercel Logo"
              className={styles.foto}
              width={250}
              height={250}
              priority
            /> */}
      {/* <Image
              src="/Wor-Foto.jpg"
              alt="Vercel Logo"
              // className={styles.foto}
              width={300}
              height={200}
              priority
            /> */}
        </div>
      </div>

      <div className={styles.center}>

      <div className={styles.description2}>
          <h1>Olá, meu nome é Worley!</h1>
          <h3>
            Estou animado para compartilhar
          </h3>
          <h3> meu portfólio com você!</h3>
     {/* <p>Ainda em construção <IoConstructOutline size={40}/></p> */}
     
      </div>
      <div className={styles.imagem}>
      <Image
              src={worfoto}
              alt="Vercel Logo"
              className={styles.foto}
              width={150}
              height={250}
              priority
            />
      </div>
      </div>

      <div className={styles.grid}>

        <div className={styles.card}>
        <a
          href={'./pageWork'}
          className={styles.cardinterno}
          // target="_blank"
          rel="noopener noreferrer"
          >
          <h2>
            Projetos <span>-&gt;</span><AiFillProject  style={{ marginLeft:10}}/>
          </h2>
          {/* <p>
            Trampos, hospedados no meu github.
          </p> */}
          <p></p>
        </a>
        </div>

          <div className={styles.card}>
        <a
          href="./sobreMim"
          // className={styles.card}
          // target="_blank"
          rel="noopener noreferrer"
        >
          <h2>
            Sobre mim <span>-&gt;</span>
          </h2>
       
        </a>
        </div>

          <div className={styles.card}>
        <a
          href="https://github.com/WorleySacramento"
          // className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2>
            Meu GitHub <span>-&gt;</span><FaGithub style={{ marginLeft:10}}/>
          </h2>
          <p>
           Meu GitHub para consultas!
          </p>
        </a>
        </div>

        <div className={styles.card}>
        <a
          href="https://www.linkedin.com/in/worley-sacramento-3b07721b7/"
          // className={styles.card}
          target="_parent"
          rel="noopener noreferrer"
        >
          <h2>
            Linkedin <span>-&gt;</span><FaLinkedin style={{ marginLeft:10}}/>
          </h2>
          <p>
           Atualizações de projetos.
          </p>
        </a>
        </div>
      </div>
    </main>
  </>;
}
